Nested logger context + refactoring
strigo/wryte pull request #39
Opened 2019-06-24 12:55 UTC by avishai-ish-shalom

Slightly changed the API of wryte, hence the minor version bump:
- Added nested logger support, see `README.md`
- While logging-time methods should never blow up (wryte core principle?), config-time methods _should_ blow up. You don't want logger config to silently fail and leave you without any logs...

2019-07-09 09:44 UTC, nir0s commented
Windows build has failed.

2019-07-10 19:29 UTC, nir0s commented
There are also many linting issues:
```
************* Module wryte
wryte.py:65:0: C0301: Line too long (139/120) (line-too-long)
wryte.py:77:0: C0330: Wrong hanging indentation.
            }
    |   |   ^ (bad-continuation)
wryte.py:288:43: C0303: Trailing whitespace (trailing-whitespace)
wryte.py:526:0: C0303: Trailing whitespace (trailing-whitespace)
wryte.py:663:0: C0303: Trailing whitespace (trailing-whitespace)
wryte.py:684:0: C0330: Wrong continued indentation (add 7 spaces).
                                    level=level, pretty=pretty,
                                    ^      | (bad-continuation)
wryte.py:685:0: C0330: Wrong continued indentation (add 7 spaces).
                                    bare=bare, jsonify=jsonify,
                                    ^      | (bad-continuation)
wryte.py:686:0: C0330: Wrong continued indentation (add 7 spaces).
                                    color=color,
                                    ^      | (bad-continuation)
wryte.py:687:0: C0330: Wrong continued indentation (add 7 spaces).
                                    simple=simple, enable_ec2=enable_ec2))
                                    ^      | (bad-continuation)
wryte.py:688:0: C0303: Trailing whitespace (trailing-whitespace)
wryte.py:63:23: W0212: Access to a protected member _nameToLevel of a client class (protected-access)
wryte.py:65:81: E1101: Module 'logging' has no '_levelNames' member (no-member)
wryte.py:65:81: W0212: Access to a protected member _levelNames of a client class (protected-access)
wryte.py:153:0: R0205: Class 'WryteLoggerEngine' inherits from object, can be safely removed from bases in python3 (useless-object-inheritance)
wryte.py:476:23: W0212: Access to a protected member _log_engine of a client class (protected-access)
wryte.py:482:0: R0205: Class 'WryteLogger' inherits from object, can be safely removed from bases in python3 (useless-object-inheritance)
```

2019-07-10 20:40 UTC, nir0s requested changes

2019-07-10 20:40 UTC, nir0s commented on Pipfile
> +[[source]]
Thanks for this :)

2019-07-10 20:40 UTC, nir0s commented on README.md
> +nested_wryter = wryter.nested(name='nested', {'user_id': framework.user}, key=value)
You have a named parameter before a non-named one :)

2019-07-10 20:40 UTC, nir0s commented on wryte.py
> +import copy
Nitpicking. We're ordering imports by length. Please move it up,

2019-07-10 20:40 UTC, nir0s commented on wryte.py
> +    LEVEL_CONVERSION = logging._nameToLevel
Wonderful!

2019-07-10 20:40 UTC, nir0s commented on wryte.py
> +    LEVEL_CONVERSION = logging._nameToLevel
Though I'd "Ask for forgiveness, not permission" here. Makes more sense to me than `hasattr`.

2019-07-10 20:40 UTC, nir0s commented on wryte.py
> +    LEVEL_CONVERSION = dict((level_str, level_num) for (level_str, level_num) in logging._levelNames.items() if isinstance(level_str, str))
This won't pass linting (max 120 chars)

2019-07-10 20:40 UTC, nir0s commented on wryte.py
> +                self.warn('_set_level set to uknown level: {}'.format(err))
uknown -> unknown

2019-07-10 20:40 UTC, nir0s commented on wryte.py
> +                self.warn('_set_level set to uknown level: {}'.format(err))
uknown -> unknown

2019-07-10 20:40 UTC, nir0s commented on wryte.py
> +class WryteLogger(object):
`(object)` is not required in Python3 (which we lint by).

2019-07-10 20:40 UTC, nir0s commented on wryte.py
> +
This upper part could be instead:
```python
self._log_context = log_engine._log # though this should no longer be private in the engine.
self._log_context.update(log_context or {})
```

2019-07-10 20:40 UTC, nir0s commented on wryte.py
> +
Oh, these are both just stuck here in the middle. I'd move them to the class definition.

2019-07-10 20:40 UTC, nir0s commented on wryte.py
> +        super().__init__(WryteLoggerEngine(name=name, hostname=hostname,
Won't work on py2.7. `super` must be passed with the class.

2019-07-10 20:40 UTC, nir0s commented on wryte.py
> +        if log_context:
This won't even work with the previously set context. You're referring to `log_context` as the only context there is, but there is also implicit context generated by `_get_base` in the engine that is exposed in `self.log_engine._log`.

This, for instance, is preventing the `ConsoleFormatter` from working at all.

2019-07-10 20:40 UTC, nir0s commented on wryte.py
> +def _proxy_method(name):
This requires a serious explanation in-code. It's clear why this is implemented only on deeper reading of the code.

2019-07-10 20:40 UTC, nir0s commented on wryte.py
> +    def get_level(self):
Great addition

2019-07-10 20:40 UTC, nir0s commented on wryte.py
> +    def get_level(self):
I'd add a docstring for consistency.

2019-07-10 20:40 UTC, nir0s commented on wryte.py
> +        self._log_context.update(self._normalize_objects(objects))
I like the name. Makes much more sense than `_log`.

2019-07-10 20:40 UTC, nir0s commented on wryte.py
> +    def nested(self, context=None, **kwargs):
Please add docstring.

2019-07-10 20:40 UTC, nir0s commented on wryte.py
> +            _context.update(context)
What if `context` isn't a dict. You thik we should let it slide?

2019-07-10 20:40 UTC, nir0s commented on wryte.py
> +
Honestly, I'm not sure I'd add the previous context implicitly. Maybe it should be sent as another argument.

2019-07-10 20:40 UTC, nir0s commented
FYI @wolf-daniel

2020-03-13 21:53 UTC, m1keil commented
going to close it for now :)

2020-03-13 21:53 UTC, closed without merging